{% set name = "dask-kubernetes" %}
{% set version = "2023.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dask-kubernetes-{{ version }}.tar.gz
  sha256: 2c14c23cc6ae4866145a487b3a62d566992c7d9799611a19b78099f9a1834e87

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - dask-core >=2022.08.1
    - distributed >=2022.08.1
    - python-kubernetes >=12.0.1
    - kubernetes_asyncio >=12.0.1
    - kopf >=1.35.3
    - pykube-ng >=22.9.0
    - rich >=12.5.1

test:
  imports:
    - dask_kubernetes
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dask/dask-kubernetes
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Native Kubernetes integration for Dask

extra:
  recipe-maintainers:
    - mrocklin
    - ocefpaf
    - jacobtomlinson
