{% set name = "dask-kubernetes" %}
{% set version = "2025.4.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: dfbe5d03af715a050b074305f6b6a81969e5d70f4a3fb079c79d97ff57d2d763

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - dask-core >=2022.08.1
    - distributed >=2022.08.1
    - python-kubernetes >=12.0.1
    - kubernetes_asyncio >=12.0.1
    - kopf >=1.35.3
    - pykube-ng >=22.9.0
    - rich >=12.5.1
    - kr8s ==0.20.*

test:
  requires:
    - python {{ python_min }}
  imports:
    - dask_kubernetes
  # Cannot use pip check b/c kr8s version is ill formed in the package.
  # dask-kubernetes 2023.6.1 has requirement kr8s==0.6.0, but you have kr8s 0.0.0.post2+7801a48.
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  home: https://github.com/dask/dask-kubernetes
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Native Kubernetes integration for Dask

extra:
  recipe-maintainers:
    - mrocklin
    - ocefpaf
    - jacobtomlinson
