{% set name = "dask-kubernetes" %}
{% set version = "2023.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dask-kubernetes-{{ version }}.tar.gz
  sha256: e74581e72eee3e2a2036be8b9dd76564a2b6c44b88aa2704a785b4824645b6de

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - dask-core >=2022.08.1
    - distributed >=2022.08.1
    - python-kubernetes >=12.0.1
    - kubernetes_asyncio >=12.0.1
    - kopf >=1.35.3
    - pykube-ng >=22.9.0
    - rich >=12.5.1
    - kr8s >=0.9.0

test:
  imports:
    - dask_kubernetes
  # Cannot use pip check b/c kr8s version is ill formed in the package.
  # dask-kubernetes 2023.6.1 has requirement kr8s==0.6.0, but you have kr8s 0.0.0.post2+7801a48.
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  home: https://github.com/dask/dask-kubernetes
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Native Kubernetes integration for Dask

extra:
  recipe-maintainers:
    - mrocklin
    - ocefpaf
    - jacobtomlinson
